=== iz5wga/RT-rfc-231/XSD/VisualizzaErogatoRichiesta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.regione.toscana.it.org/sisrt/sea"
	    xmlns="http://www.w3.org/2001/XMLSchema" 
	    xmlns:sisrt-ric="http://www.regione.toscana.it.org/sisrt/sea"
	    xmlns:sisrt="http://www.regione.toscana.it.org/sisrt/generic"
	    elementFormDefault="qualified" 
	    attributeFormDefault="unqualified">

	<import schemaLocation="TipiDatiVisualizzaErogato.xsd"
		namespace="http://www.regione.toscana.it.org/sisrt/generic"></import>
	<annotation>
		<documentation>Versione 1.2</documentation>
	</annotation>
	<element name="VisualizzaErogatoRichiesta">
		<annotation>
			<documentation>
			    Elemento base per la richiesta di visualizzazione
				della ricetta prescritta dal medico da parte dell'erogatore
			</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element name="codiceAslErogatore"
					type="sisrt:stringType">
					<annotation>
						<documentation>
							Codice ASL della struttura erogatrice
						</documentation>
					</annotation>
				</element>
				<element name="codiceSsaErogatore"
					type="sisrt:stringType">
					<annotation>
						<documentation>
							Codice SSA della struttura erogatrice
						</documentation>
					</annotation>
				</element>
                <element name="pwd" type="sisrt:pwdType" minOccurs="0"></element>
                <element name="nre" type="sisrt:nreType">
					<annotation>
						<documentation>
							Numero Ricetta Elettronica
						</documentation>
					</annotation>
				</element>
				<element name="cfAssistito" type="sisrt:stringType"
					minOccurs="0">
					<annotation>
						<documentation>
							Codice fiscale dellâ€™assistito prelevato
							dalla Tessera Sanitaria
						</documentation>
					</annotation>
				</element>
				<element name="tipoOperazione"
					type="sisrt:tipoOperazioneType">
					<annotation>
						<documentation>
							10 - Visualizzazione della ricetta senza
							cambio di stato 11 - Comunicazione di
							visualizzazione e presa in carico della
							ricetta e recupero completo dei dati 12 -
							Comunicazione di visualizzazione e presa in
							carico della ricetta senza recupero completo
							dei dati 13 - Rilascio di una ricetta
							precedentemente presa in carico / prenotata
							14 - Visualizzazione dei dati dell'assistito
							oscurati dal medico 15 - Prenotazione di una
							prestazione ad opera di un CUP 16 -
							Comunicazione di visualizzazione e presa in
							carico della ricetta e recupero completo dei
							dati, non esclusiva 17 - Comunicazione di
							visualizzazione e presa in carico della
							ricetta senza recupero completo dei dati,
							non esclusiva.
						</documentation>
					</annotation>
				</element>
				<element name="prenotazione"
					type="sisrt:prenotazioneType" minOccurs="0"
					maxOccurs="unbounded">
				</element>
				<element name="flagEsclusivita"
					type="sisrt:flagEsclusivita" default="0">
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== iz5wga/RT-rfc-231/Esempi/VisualizzaErogatoRichiesta_tpOp11.xml
<?xml version="1.0" encoding="UTF-8"?>
<sisrt-ric:VisualizzaErogatoRichiesta xmlns:sisrt="http://www.regione.toscana.it.org/sisrt/generic" xmlns:sisrt-ric="http://www.regione.toscana.it.org/sisrt/sea" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.regione.toscana.it.org/sisrt/sea ../XSD/VisualizzaErogatoRichiesta.xsd ">
  <sisrt-ric:codiceAslErogatore>108</sisrt-ric:codiceAslErogatore>
  <sisrt-ric:codiceSsaErogatore>108</sisrt-ric:codiceSsaErogatore>
  <sisrt-ric:pwd>AAABBB11L45F656Y</sisrt-ric:pwd>
  <sisrt-ric:nre>090123456789012</sisrt-ric:nre>
  <sisrt-ric:cfAssistito>PPRPPR26S16D118H</sisrt-ric:cfAssistito>
  <sisrt-ric:tipoOperazione>11</sisrt-ric:tipoOperazione>
  <sisrt-ric:flagEsclusivita>0</sisrt-ric:flagEsclusivita>
</sisrt-ric:VisualizzaErogatoRichiesta>
